# Generated by Django 3.0.3 on 2020-08-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnniversaryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_title', models.CharField(max_length=128)),
                ('cake_price', models.CharField(max_length=512)),
                ('cake_photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='BirthdayTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_title', models.CharField(max_length=128)),
                ('cake_price', models.CharField(max_length=512)),
                ('cake_photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='InstaTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('Phone', models.CharField(max_length=128)),
                ('Details', models.CharField(max_length=1024, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=1024, null=True)),
                ('message', models.CharField(max_length=1024, null=True)),
                ('cake_weight', models.IntegerField(choices=[(1, 'Select cake weight in pound'), (1, '1 pound'), (2, '2 pound'), (3, '3 pound'), (4, '4 pound'), (5, '5 pound')], default=1, max_length=10)),
                ('amount', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_title', models.CharField(max_length=128)),
                ('cake_price', models.CharField(max_length=512)),
                ('cake_photo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
